// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/home/domain/entities/work_session.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1872548153814207866),
    name: 'WorkSession',
    lastPropertyId: const obx_int.IdUid(9, 8989960893818791690),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2050401674030864008),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1249924432425392579),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1667105029599052161),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5775258724215118423),
        name: 'checkInTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4657674639343256804),
        name: 'checkOutTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9161682839446226802),
        name: 'breakStartTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2352911564651459814),
        name: 'totalBreakDuration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4632678079777807587),
        name: 'workDuration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8989960893818791690),
        name: 'isSyncedWithFirebase',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 1872548153814207866),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    WorkSession: obx_int.EntityDefinition<WorkSession>(
      model: _entities[0],
      toOneRelations: (WorkSession object) => [],
      toManyRelations: (WorkSession object) => {},
      getId: (WorkSession object) => object.id,
      setId: (WorkSession object, int id) {
        object.id = id;
      },
      objectToFB: (WorkSession object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userIdOffset);
        fbb.addInt64(2, object.date.millisecondsSinceEpoch);
        fbb.addInt64(3, object.checkInTime?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.checkOutTime?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.breakStartTime?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.totalBreakDuration);
        fbb.addInt64(7, object.workDuration);
        fbb.addBool(8, object.isSyncedWithFirebase);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final checkInTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final checkOutTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final breakStartTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final checkInTimeParam = checkInTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(checkInTimeValue);
        final checkOutTimeParam = checkOutTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(checkOutTimeValue);
        final breakStartTimeParam = breakStartTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(breakStartTimeValue);
        final totalBreakDurationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final workDurationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final isSyncedWithFirebaseParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = WorkSession(
          id: idParam,
          userId: userIdParam,
          date: dateParam,
          checkInTime: checkInTimeParam,
          checkOutTime: checkOutTimeParam,
          breakStartTime: breakStartTimeParam,
          totalBreakDuration: totalBreakDurationParam,
          workDuration: workDurationParam,
          isSyncedWithFirebase: isSyncedWithFirebaseParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [WorkSession] entity fields to define ObjectBox queries.
class WorkSession_ {
  /// See [WorkSession.id].
  static final id = obx.QueryIntegerProperty<WorkSession>(
    _entities[0].properties[0],
  );

  /// See [WorkSession.userId].
  static final userId = obx.QueryStringProperty<WorkSession>(
    _entities[0].properties[1],
  );

  /// See [WorkSession.date].
  static final date = obx.QueryDateProperty<WorkSession>(
    _entities[0].properties[2],
  );

  /// See [WorkSession.checkInTime].
  static final checkInTime = obx.QueryDateProperty<WorkSession>(
    _entities[0].properties[3],
  );

  /// See [WorkSession.checkOutTime].
  static final checkOutTime = obx.QueryDateProperty<WorkSession>(
    _entities[0].properties[4],
  );

  /// See [WorkSession.breakStartTime].
  static final breakStartTime = obx.QueryDateProperty<WorkSession>(
    _entities[0].properties[5],
  );

  /// See [WorkSession.totalBreakDuration].
  static final totalBreakDuration = obx.QueryIntegerProperty<WorkSession>(
    _entities[0].properties[6],
  );

  /// See [WorkSession.workDuration].
  static final workDuration = obx.QueryIntegerProperty<WorkSession>(
    _entities[0].properties[7],
  );

  /// See [WorkSession.isSyncedWithFirebase].
  static final isSyncedWithFirebase = obx.QueryBooleanProperty<WorkSession>(
    _entities[0].properties[8],
  );
}
